name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: setup go 
        uses: actions/setup-go@v5

      - name: setup build script for notely
        run: ./scripts/buildprod.sh
